2019-11-23 11:28:52,860 ERROR 826 [egg-mongoose] mongodb://127.0.0.1:27017/mongooseTest disconnected
2019-11-23 11:28:52,862 ERROR 826 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:189:13)
    at createConnection (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:562:14)
    at connect (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:985:11)
    at makeConnection (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 826
hostname: kubandeMacBook-Pro.local

2019-11-23 11:28:52,863 ERROR 826 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:189:13)
    at createConnection (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:562:14)
    at connect (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:985:11)
    at makeConnection (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 826
hostname: kubandeMacBook-Pro.local

2019-11-23 11:28:52,865 ERROR 826 [-/127.0.0.1/-/1ms GET /] nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:189:13)
    at createConnection (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:562:14)
    at connect (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:985:11)
    at makeConnection (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/Users/kuban/Desktop/interviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 826
hostname: kubandeMacBook-Pro.local

2019-12-09 16:28:58,814 ERROR 10668 [-/127.0.0.1/-/7ms GET /js] nodejs.TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at respond (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:259:15)
    at handleResponse (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:164:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 10668
hostname: kubandeMacBook-Pro.local

2019-12-09 16:30:03,238 ERROR 10672 [-/127.0.0.1/-/7ms GET /js] nodejs.TypeError: Cannot read property 'find' of undefined
    at JsController.index (/Users/kuban/Desktop/InterviewQuestionManage/app/controller/js.js:8:37)
    at Object.callFn (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa-compose/index.js:44:32)
    at next (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa-compose/index.js:45:18)
    at /Users/kuban/Desktop/InterviewQuestionManage/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa-compose/index.js:44:32)
    at /Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/kuban/Desktop/InterviewQuestionManage/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/node_modules/koa-compose/index.js:42:32)

pid: 10672
hostname: kubandeMacBook-Pro.local

2019-12-09 16:31:11,111 ERROR 10679 [-/127.0.0.1/-/9ms GET /js] nodejs.TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at respond (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:259:15)
    at handleResponse (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:164:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 10679
hostname: kubandeMacBook-Pro.local

2019-12-10 04:55:36,703 ERROR 10590 nodejs.ClusterClientNoResponseError: client no response in 43264348ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10590
hostname: kubandeMacBook-Pro.local

2019-12-10 08:24:42,739 ERROR 10590 nodejs.ClusterClientNoResponseError: client no response in 12546016ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10590
hostname: kubandeMacBook-Pro.local

2019-12-10 11:04:04,819 ERROR 10590 nodejs.ClusterClientNoResponseError: client no response in 9522063ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10590
hostname: kubandeMacBook-Pro.local

2019-12-10 11:06:25,675 ERROR 10590 nodejs.ClusterClientNoResponseError: client no response in 140851ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10590
hostname: kubandeMacBook-Pro.local

2019-12-15 12:32:15,965 ERROR 37080 [-/127.0.0.1/-/10ms GET /] nodejs.TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at respond (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:259:15)
    at handleResponse (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:164:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 37080
hostname: kubandeMacBook-Pro.local

2019-12-15 12:34:34,487 ERROR 37080 [-/127.0.0.1/-/2ms GET /js] nodejs.TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at respond (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:259:15)
    at handleResponse (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:164:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 37080
hostname: kubandeMacBook-Pro.local

2019-12-15 12:43:23,774 ERROR 643 [-/127.0.0.1/-/14ms GET /] nodejs.TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at respond (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:259:15)
    at handleResponse (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/koa/lib/application.js:164:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 643
hostname: kubandeMacBook-Pro.local

2019-12-15 13:42:23,854 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 314853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-15 14:02:26,195 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 1162288ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-15 14:05:12,134 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 145927ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-15 14:18:27,337 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 755155ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-15 14:21:19,092 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 151732ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-15 14:33:30,291 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 691178ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-15 14:44:10,411 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 620110ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-15 14:53:13,803 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 503293ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-15 14:55:39,449 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 125637ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-16 02:56:39,573 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 43259961ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-16 08:45:03,779 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 20904159ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-16 10:15:02,041 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 5398254ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-16 10:17:16,568 ERROR 642 nodejs.ClusterClientNoResponseError: client no response in 95130ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 642
hostname: kubandeMacBook-Pro.local

2019-12-19 00:57:33,006 ERROR 13194 nodejs.ClusterClientNoResponseError: client no response in 7219057ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 13194
hostname: kubandeMacBook-Pro.local

2019-12-19 09:15:10,566 ERROR 13194 nodejs.ClusterClientNoResponseError: client no response in 29857488ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 13194
hostname: kubandeMacBook-Pro.local

2019-12-19 10:06:28,604 ERROR 13194 nodejs.ClusterClientNoResponseError: client no response in 3078006ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 13194
hostname: kubandeMacBook-Pro.local

2019-12-20 01:29:37,350 ERROR 18372 nodejs.ClusterClientNoResponseError: client no response in 7211669ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 18372
hostname: kubandeMacBook-Pro.local

2019-12-20 08:45:09,452 ERROR 18372 nodejs.ClusterClientNoResponseError: client no response in 26132084ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 18372
hostname: kubandeMacBook-Pro.local

2019-12-20 10:22:03,200 ERROR 18372 nodejs.ClusterClientNoResponseError: client no response in 5813731ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 18372
hostname: kubandeMacBook-Pro.local

