2020-08-02 10:10:07,468 INFO 12818 [egg-logrotator] agent logger reload: got log-reload message
2020-08-02 10:32:14,416 ERROR 12818 nodejs.ClusterClientNoResponseError: client no response in 151247ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 12818
hostname: senge.local

2020-08-02 11:11:29,557 ERROR 12818 nodejs.ClusterClientNoResponseError: client no response in 2314877ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 12818
hostname: senge.local

2020-08-02 11:46:31,444 ERROR 12818 nodejs.ClusterClientNoResponseError: client no response in 2061869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 12818
hostname: senge.local

2020-08-02 17:36:07,225 INFO 12818 [egg-watcher] Recieved a change event from eventSource: {"event":"change","path":"/Users/kuban/Desktop/InterviewQuestionManage/app/model/js.js","stat":{"dev":16777222,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":12904945291,"size":248,"blocks":8,"atimeMs":1596360967220.1096,"mtimeMs":1596360967159.049,"ctimeMs":1596360967159.049,"birthtimeMs":1575877874257.1362,"atime":"2020-08-02T09:36:07.220Z","mtime":"2020-08-02T09:36:07.159Z","ctime":"2020-08-02T09:36:07.159Z","birthtime":"2019-12-09T07:51:14.257Z"},"remove":false,"isDirectory":false,"isFile":true}
2020-08-02 17:36:07,436 WARN 12818 [agent:development] reload worker because /Users/kuban/Desktop/InterviewQuestionManage/app/model/js.js change
2020-08-03 06:22:47,422 ERROR 12818 nodejs.ClusterClientNoResponseError: client no response in 17474814ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 12818
hostname: senge.local

2020-08-03 08:32:52,123 ERROR 12818 nodejs.ClusterClientNoResponseError: client no response in 7764685ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 12818
hostname: senge.local

2020-08-03 08:39:33,961 ERROR 12818 nodejs.ClusterClientNoResponseError: client no response in 302602ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 12818
hostname: senge.local

2020-08-03 09:34:40,908 ERROR 12818 nodejs.ClusterClientNoResponseError: client no response in 3286939ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 12818
hostname: senge.local

