2020-09-06 09:45:53,949 INFO 628 [egg-logrotator] agent logger reload: got log-reload message
2020-09-06 14:56:17,140 ERROR 628 nodejs.ClusterClientNoResponseError: client no response in 10278294ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 628
hostname: senge.local

2020-09-06 15:17:51,627 INFO 628 [egg-watcher] Recieved a change event from eventSource: {"event":"rename","path":"/Users/kuban/Desktop/InterviewQuestionManage/app/public/uploads/1599376671564.png","stat":{"dev":16777222,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":12934519488,"size":386351,"blocks":760,"atimeMs":1599376671627.2576,"mtimeMs":1599376671570.046,"ctimeMs":1599376671570.046,"birthtimeMs":1599376671565.8518,"atime":"2020-09-06T07:17:51.627Z","mtime":"2020-09-06T07:17:51.570Z","ctime":"2020-09-06T07:17:51.570Z","birthtime":"2020-09-06T07:17:51.566Z"},"remove":false,"isDirectory":false,"isFile":true}
2020-09-07 03:51:54,006 ERROR 628 nodejs.ClusterClientNoResponseError: client no response in 43275755ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 628
hostname: senge.local

2020-09-07 09:34:43,879 ERROR 628 nodejs.ClusterClientNoResponseError: client no response in 20569865ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 628
hostname: senge.local

2020-09-07 18:50:35,121 ERROR 628 nodejs.ClusterClientNoResponseError: client no response in 86993ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 628
hostname: senge.local

2020-09-07 22:07:47,030 ERROR 628 nodejs.ClusterClientNoResponseError: client no response in 11791812ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 628
hostname: senge.local

2020-09-07 23:27:44,792 ERROR 628 nodejs.ClusterClientNoResponseError: client no response in 3137541ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 628
hostname: senge.local

2020-09-08 09:37:29,560 ERROR 628 nodejs.ClusterClientNoResponseError: client no response in 34224498ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 628
hostname: senge.local

